name: Prolog Syntax Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up SWI-Prolog
      uses: Amourspirit/setup-swi-prolog@v1
      with:
        swi-prolog-version: '8.4.2'
    - name: Check Prolog Syntax
      run: swipl -g "consult(code/travel_planner.pl), halt(0)" -t "halt(1)"
